ads/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.ads, name='ads'),
]

expads/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.expads, name='expads'),
    path('category/<slug:slug>/', views.expads, name='expads_by_category'),
    path('expatad/<int:id>/', views.expataddetail, name='expataddetail'),
    path('<int:id>/', views.deletead, name='deletead'),
    path('update/<int:id>/', views.updatead, name='updatead'),
    path('delete/<int:id>/', views.delete_ad, name='delete_ad'),
    path('edit_ad/<int:id>/', views.edit_ad, name='edit_ad'),



    #path('<slug:slug>/', views.store, name='products_by_category'),
    #path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    #path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    #path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search'),
    path('addads/', views.addads, name='addads'),
    path('placeads/', views.placeads, name='placeads'),
    path('contactme/', views.contactme, name='contactme'),
    path('contactyou/', views.contactyou, name='contactyou'),
    path('contactmes/', views.contactmes, name='contactmes'),
    path('interested/<int:id>/', views.interested, name='interested'),

    path('cities/', views.cities, name='cities'),
    #path('submit_review/<int:product_id>/', views.submit_review, name='submit_review'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'), # AJAX

]

main/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path('',views.home,name='home'),
    path('', include('accounts.urls')),
    path('ads/', include('ads.urls')),

    path('bbg/', include('bbg.urls')),
    path("expads/", include('expads.urls')), 
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

expads/models.py
from django.db import models
#from django.contrib.auth.models import User
from accounts.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse
from sorl.thumbnail import get_thumbnail

from phonenumber_field.modelfields import PhoneNumberField

class Countrycode(models.Model):
    name = models.CharField(max_length=128)
    
    def __str__(self):
         return self.name

class Purpose(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
         return self.name


class CityCode(models.Model):
    name = models.CharField(max_length=128)
    countrycode = models.ForeignKey(Countrycode, on_delete=models.CASCADE, related_name='countrycode')

    def __str__(self):
         return self.name


class LocationCode(models.Model):
    name = models.CharField(max_length=128)
    locationcode = models.ForeignKey(CityCode, on_delete=models.CASCADE, related_name='locationcode')

    def __str__(self):
         return self.name


class SubLocationCode(models.Model):
    name = models.CharField(max_length=128)
    sublocationCode = models.ForeignKey(LocationCode, on_delete=models.CASCADE, related_name='sublocationCode')

    def __str__(self):
         return self.name


class Category(models.Model):
    name = models.CharField(max_length = 150 , null = False)
    slug = models.CharField(max_length = 150 , null = False , unique = True)
    thumbnail = models.ImageField(upload_to='users/thumnail', blank=True, null=True)   
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ('-created','-updated')
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        
    def clean(self):
        self.category_name = self.name.capitalize()

    def get_url(self):
        return reverse('expads_by_category', args=[self.slug])

    def __str__(self):
        return self.name

class Expatad(models.Model):
    user = models.ForeignKey(User ,  on_delete=models.CASCADE)
    category = models.ForeignKey(Category ,  on_delete=models.CASCADE)
    fullname = models.CharField(max_length=150)
    countrycode = models.ForeignKey(Countrycode ,default='Saudi Arabia',  on_delete=models.CASCADE)
    purpose = models.ForeignKey(Purpose , on_delete=models.CASCADE)
    citycode = models.ForeignKey(CityCode ,  default='Jeddah',on_delete=models.CASCADE)
    locationcode =models.CharField(max_length=200)
    sublocationcode = models.CharField(max_length=200)
    landmark = models.CharField(max_length=200)
    area = models.CharField(max_length=100,default=100)
    areameasurement = models.CharField(max_length=40,default='Square Feet')
    contactno = PhoneNumberField()
    zipcode = models.CharField(max_length=20)
    price = models.DecimalField(max_digits=15, decimal_places=2)
    Description = models.CharField(max_length=500)
    is_active = models.BooleanField(default=True)
    cover_photo = models.ImageField(upload_to='users/cover_photos', blank=True, null=True)    
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ('-created','-updated')
        verbose_name = 'expatad'
        verbose_name_plural = 'expatads'

    def __str__(self):
        return self.fullname

    def delete(self):
        self.cover_photo.delete()
        super().delete()


class ExpatImage(models.Model):
    expatads = models.ForeignKey(Expatad, on_delete=models.CASCADE,related_name='expatads')
    images = models.FileField(upload_to='users/images', blank=True, null=True)

    

    @property
    def thumbnail(self):
        if self.images:
            return get_thumbnail(self.images, '50x50', quality=90)
        return None
    
    def __str__(self):
        return self.expatads.contactno


 #   def delete(self):
        self.cover_photo.delete()
        super().delete()
 #       
 #   year = models.PositiveSmallIntegerField(
 #       validators=[
 #           MinValueValidator(1895),
 #           MaxValueValidator(2050),
 #       ])

 #   rating = models.PositiveSmallIntegerField(choices=(
 #       (1, "★☆☆☆☆"),
 #       (2, "★★☆☆☆"),
 #       (3, "★★★☆☆"),
 #       (4, "★★★★☆"),
 #       (5, "★★★★★"),        



class Contactme(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    fullname = models.CharField(max_length=150)
    contactno = PhoneNumberField()
    email = models.CharField(max_length=150)
    Description = models.CharField(max_length=500)
    is_fallowed = models.CharField(max_length=100,default="Yet Not Followed This Message")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.fullname

class Interested(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    fullname = models.CharField(max_length=150)
    contactno = PhoneNumberField()
    email = models.CharField(max_length=150)
    Description = models.CharField(max_length=500)
    is_fallowed = models.CharField(max_length=100,default="Yet Not Followed This Message")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.fullname

expads/views.py
import json
from .forms import ExpatadForm,ContactmeForm,InterestedForm
from django.shortcuts import render, redirect,get_object_or_404,redirect,HttpResponseRedirect
from .models import Expatad, Category,ExpatImage,Contactme,Countrycode,CityCode,Interested,Purpose #ReviewRating, ProductGallery
from django.contrib.auth.models import User
from main.filters import Expatadfilter

from django.db.models import Q


from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from accounts.utils import send_mail,send_notification
from django.contrib.sites.shortcuts import get_current_site

from django.db import transaction

from main.filters import Expatadfilter
def expads(request, slug=None):
    categories = None
    expatads = None
    if slug != None:
        categories = get_object_or_404(Category, slug=slug)
        #print(categories)
        #expatads = Expatad.objects.filter(category=categories, is_active=True)
        expatad_filter = Expatadfilter(request.GET, queryset=Expatad.objects.all().filter(category=categories,is_active=True))
        expatads = expatad_filter.qs
        paginator = Paginator(expatads, 10)
        page = request.GET.get('page')
        paged_expatads = paginator.get_page(page)
        expatad_count = expatads.count()
    else:
        expatad_filter = Expatadfilter(request.GET, queryset=Expatad.objects.all().filter(is_active=True))
        expatads = expatad_filter.qs
        paginator = Paginator(expatads, 10)
        page = request.GET.get('page')
        paged_expatads = paginator.get_page(page)
        expatad_count = expatads.count()
    context = {
        'expatads': paged_expatads,
        'expatad_count': expatad_count,
        'form' : expatad_filter.form,
        'expatads_list': expatad_filter.qs,
    }
    return render(request, 'home.html', context)

def expataddetail(request,id):
    expatads = get_object_or_404(Expatad,id=id) 
    expatImage_list =ExpatImage.objects.filter(expatads=expatads).prefetch_related('expatads')
    #print(request.user)
    #print(expatads.user)
    if request.user==expatads.user:
        uservalue=True
    else:
        uservalue=False
    #ExpatImage.objects.filter(ExpatImage=Expatad)
    #ExpatImage.objects.filter(ExpatImage=Expatad).prefetch_related('vehiclepart_set')
    #expatImage_list = ExpatImage.objects.filter(id=expatads.id)
    #print(expatImage_list.images)
    #print(expatads.id)
    #print(uservalue)
    context = {'expatads':expatads,'expatImage_list': expatImage_list,'uservalue':uservalue}
    return render(request, 'expads/expataddetail.html',context)

def search(request):
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            expads = Expatad.objects.order_by('-created').filter(Q(Description__icontains=keyword) | Q(fullname__icontains=keyword))
            expad_count = expads.count()
            print("Found")
    context = {
        'expatads': expads,
        'expatad_count': expad_count,
    }
    return render(request, 'home.html', context)


def contactme(request):
    context = {

        }
    return render(request, 'expads/contactme.html', context)

def contactyou(request):
    context = {

        }    
    return render(request, 'expads/contactyou.html', context)

def contactmes(request):
#    obj = get_object_or_404(Contactme, id = id)
    form = ContactmeForm()
    if request.method == 'POST' and request.user.is_authenticated:
        form = ContactmeForm(request.POST)
        email = form.data['email']
        request.POST._mutable = True
        #user = User.objects.get(id=request.data['user']) # that is if you are sending the use Id from the frontend
        form.data['user']=request.user
        form.data['is_followed']=False
        if form.is_valid():
            form.save()
            mail_subject = 'We have received your Email'
            email_template = 'accounts/emails/contactusconfirm.html'
            #send_confirm_email(request, contactus, mail_subject, email_template)
            print(Contactme)
            send_mail(mail_subject,'We received Your message Here is acknowledgment Thanks','aakhan1572@gmail.com',[email],fail_silently=False,)
            messages.success(request, 'We have received your message sucessfully!')
            return redirect('contactmes')

    if not request.user.is_authenticated:
        messages.success(request, 'Please login')
        return render(request, 'accounts/login.html')
    context = {'form': form}
    return render(request, 'expads/contactmes.html', context)

def interested(request,id):
    expatads = get_object_or_404(Expatad,id=id) 
    form = InterestedForm()
    if request.method == 'POST' and request.user.is_authenticated:
        form = InterestedForm(request.POST)
        email = form.data['email']
        mobilenumber=expatads.contactno
        citycodet=expatads.citycode
        locationcodet=expatads.locationcode
        sublocationcodet=expatads.sublocationcode
        landmarkt=expatads.landmark
        pricet=expatads.price

        request.POST._mutable = True
        form.data['user']=request.user
        form.data['is_followed']=False
        context={'user': request.user,
                 'locationcode' : locationcodet,
                 'sublocationcode' : sublocationcodet,
                 'landmark' : landmarkt,
                 'price' : pricet,
                 'citycode':citycodet,
                 'fromemail': request.user.email,
                 'to_email':email,
                 'mobilenumber': mobilenumber,
                 'domain':get_current_site(request)}
        if form.is_valid():
            form.save()
            mail_subject = 'We have received your Email '
            email_template = 'accounts/emails/Sendnotification_to_customer.html'
          
            send_notification(mail_subject, email_template, context)
            #send_mail(mail_subject,'We received Your message Here is acknowledgment Thanks','aakhan1572@gmail.com',[email],fail_silently=False,)
            messages.success(request, 'We have received your message sucessfully!')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    if not request.user.is_authenticated:
        messages.success(request, 'Please login')
        return render(request, 'accounts/login.html')
    context = {'form': form}
    return render(request, 'expads/interested.html', context)

@login_required(login_url='login')
def addads(request):
    form=ExpatadForm()
    if request.method == "POST":
        form= ExpatadForm(request.POST,request.FILES)
        images_list = request.FILES.getlist('images')
        request.POST._mutable = True
        form.data['user']=request.user
        form.data['is_active']=True
        if form.is_valid():
            newform=form.save()
            expatad = Expatad.objects.get(id=newform.id)
            for image in images_list:
                Expatad_images = ExpatImage.objects.create(
                    expatads= expatad,
                    images = image

                )
            messages.success(request, 'Your Ad added successfully.')
            return redirect('expataddetail',id=expatad.id)
        #else:
            #messages.error(request,'Enter Valid Data')
            #return redirect(request.META['HTTP_REFERER'])
            #return HttpResponse('Form Not Valid')
    else:
        form = ExpatadForm()
    countrycodes=Countrycode.objects.all()
    context = {'form':form,'countrycodes':countrycodes}
    return render(request, 'expads/addads.html',context)

# AJAX
def load_cities(request):
    country_id = request.GET.get('countrycode')
    cities = CityCode.objects.filter(countrycode_id=country_id).all()
    return render(request, 'expads/city_dropdown_list_options.html', {'cities': cities})

def placeads(request):
    if request.method == "POST":
        fullname1 = request.POST['fullname']
        city = request.POST['cityname']
        measurements = request.POST['measurements']
        print(fullname1, city, measurements) 
    countrycodes=Countrycode.objects.all()
    context = {'countrycodes':countrycodes}
    return render(request, 'expads/placeads.html',context)

@login_required(login_url='login')
def deletead(request,id):
    if request.method =='POST':
        messages.success(request, 'Your Posted Ad Delete Successfully')
        print(id)
        pi=Expatad.objects.get(id=id)
        pi.delete()
        messages.success(request, 'Your Posted Ad Delete Successfully')
    else:
        messages.success(request, 'Your not owner of this Ad')
    return redirect('home')

@login_required(login_url='login')
def delete_ad(request, id):
    expatad = get_object_or_404(Expatad, id=id)
    print(id)
    expatad.delete()
    messages.success(request, 'Your Ad has been deleted successfully!')
    return redirect('home')

@login_required(login_url='login')
def updatead(request,id):
    pi = get_object_or_404(Expatad,id=id)
    if request.method == 'POST':
        pi = Expatad.objects.get(id=id)
        fm = ExpatadForm(request.POST,request.FILES,instance=pi)
        images_list = request.FILES.getlist('images')
        request.POST._mutable = True
        fm.data['user']=request.user
        fm.data['is_active']=True
        if fm.is_valid():
            expatad = Expatad.objects.get(id=id)
            exp=Expatad.objects.get(id=id)
            exp.delete()
            fm.save()
            for image in images_list:
                Expatad_images = ExpatImage.objects.create(
                    expatads= expatad,
                    images = image
                )
            messages.success(request, 'Your Ad Updated successfully.')
            return redirect('updatead',id=id)
        else:
            print('invalid form')
            print(fm.errors)

templates/expads/addads.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!-- Main Section Start -->
<div class="main-section">
    <div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 60px;margin-bottom: 0px;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                    <div class="user-dashboard loader-holder">
                        <div class="user-holder">
                    <h4 class="text-center" style="margin-bottom: 0;">WELCOME TO HYDERABADIES IN SAUDI</h4>
                    <p class="text-center">Please Place your ads details</p>
                    <hr><br><br>
                    <div id="restaurant-sets-holder" class="container"> 
                        <form action="#" id="MemberForm" data-cities-url="{% url 'ajax_load_cities' %}"  class="form-fields-set foodbakery-dev-restaurant-form" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <ul class="register-add-restaurant-tab-container restaurant-information-tab-container">
                                <li>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                <ul >
                                                    <li>
                                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Full name / Project Name / Venture Name</label>{{form.fullname}}
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Sale / Buy / Rent / Wanted</label>{{form.purpose}}
                                                            </div>
                                                        </div>

                                                    </li>

                                                    <li>
                                                      <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                        <div class="field-holder">
                                                            <label>Category Type</label>{{form.category}}
                                                        </div>
                                                      </div>
                                                      <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                        <div class="field-holder">
                                                            <label>Country name</label>{{form.countrycode}}
                                                            


                                                        </div>
                                                      </div>  
                                                      <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                        <div class="field-holder">
                                                            <label>City Name</label>{{form.citycode}}
                                                        </div>
                                                      </div>
                                                      <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                        <div class="field-holder">
                                                            <label>Site Location</label>{{form.locationcode}}
                                                        </div>
                                                      </div>                                                                                                          
                                                    </li>
                                                


                                                    <li>
                                                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                                            <div class="field-holder">
                                                              <label>Site SubLocation</label>{{form.sublocationcode}}
                                                            </div>
                                                        </div>                                                        
                                                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                                          <div class="field-holder">
                                                            <label>Landmark</label>{{form.landmark}}
                                                          </div>
                                                       </div>
                                                    </li>


                                                    <li>
                                                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                                          <div class="field-holder">
                                                            <label>Area Measurements</label>{{form.areameasurement}}
                                                          </div>
                                                        </div>
                                                    
                                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Area</label>{{form.area}}
                                                            </div>
                                                        </div>
                                                    </li>

                                                    <li>                                                        
                                                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                                          <div class="field-holder">
                                                            <label>Price (Total Price)</label>{{form.price}}
                                                          </div>
                                                        </div>                                                        
                                                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                                          <div class="field-holder">
                                                            <label>ZipCode</label>{{form.zipcode}}
                                                          </div>
                                                        </div>
                                                    </li>

                                                    <li>
                                                        <div class="col-lg-6 col-md-6 col-sm-12">
                                                            <div class="field-holder">
                                                                <label >Cover_Image</label>
                                                                {{form.cover_photo}}
                                                            </div>
                                                        </div>     
                                                        <div class="col-lg-6 col-md-6 col-sm-12">
                                                            <div class="field-holder">
                                                                <label >Choose Other Images</label>
                                                                <input type="file" name="images" id="" class ="form-control" multiple>
                                                            </div>
                                                        </div>                                                                                                           

                                                    </li> 
                                                
                                                    <li>                                                
                                                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Project / Venture Description</label>{{form.Description}}
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Contact No (Ex : +91**********)</label>{{form.contactno}}
                                                            </div>
                                                        </div>                                                        
                                                    </li>


                                                </ul>
                                        </div>
                                    </div>
                                </li>

                                            <ul class="errorlist">
                                                {% for field in form %}
                                                    {% if field.errors %}
                                                        {% for error in field.errors %}
                                                            <li style="color: red;">{{error}}</li>
                                                        {% endfor %}
                                                    {% endif %}
                                                {% endfor %}

                                                <li style="color: red;">{{form.non_field_errors}}</li>
                                            </ul>

                                        <div class="row">
                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                <div class="field-holder">
                                                    <div class="payment-holder">
                                                        <input type="submit" value="Submit" id="btn-next-restaurant-information" class="bgcolor">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                <!-- Load message -->
                                                {% include 'includes/alerts.html' %}
                                            </div>
                                        </div>

                                </li>
                            </ul>
                        </form>
                    </div>
                </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Main Section End -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_countrycode").change(function () {
        const url = $("#MemberForm").attr("data-cities-url");  // get the url of the `load_cities` view
        const countryId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /members/ajax/load-cities/ )
            data: {
                'countrycode': countryId       // GET parameters
            },
            success: function (data) {   
                $("#id_citycode").html(data); 
            }
        });

    });



 /*    $(document).ready(function() {
        // messages timeout for 10 sec
        setTimeout(function() {
            $('.messages').fadeOut('slow');
        }, 8000); // <-- time in milliseconds, 1000 =  1 sec
    }); */

    
</script>  

{% endblock %}

templates/expads/categorydetail.html
<p>{{Datasample}}</p>

templates/expads/city_dropdown_list_options.html
<option value="">---------</option>
{% for citycode in cities %}
    <option value="{{ citycode.id }}">{{ citycode.name }}</option>
{% endfor %}

templates/expads/contactyous.html
<p>Contact You</p>
<h1>{{expatads.fullname}}</h1>